version: "3.9"

services:
  db:
    image: postgres:18
    container_name: nba_postgres
    restart: always
    environment:
      POSTGRES_DB: nba
      POSTGRES_USER: amirhosssein
      POSTGRES_PASSWORD: Asdfghjkl0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: nba_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: nba
      DB_USER: amirhosssein
      DB_PASSWORD: Asdfghjkl0
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data: