services:
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      # Database configuration matching Django settings.py
      - DB_NAME=nba
      - DB_USER=amirhosssein
      - DB_PASSWORD=Asdfghjkl0
      - DB_HOST=db
      - DB_PORT=5432
      # Security settings
      - SECRET_KEY=your-secret-key-change-in-production
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: docker.iranrepo.ir/library/postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nba
      - POSTGRES_USER=amirhosssein
      - POSTGRES_PASSWORD=Asdfghjkl0

volumes:
  postgres_data:
  static_volume:
  media_volume: